//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clientes()
        {
            this.despacho = new HashSet<despacho>();
        }
        [Required]
        public decimal codigo_cliente { get; set; }
        [Required]
        public string nombre_cliente { get; set; }
        [Required]
        public string apellido_cliente { get; set; }
        [Required]
        public string direcc_cliente { get; set; }
        [Required]
        public string telef_cliente { get; set; }
        [Required]
        public string correo_cliente { get; set; }
        [Required]
        public string tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<despacho> despacho { get; set; }
    }
}
