//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class despacho
    {
        public int id { get; set; }
        public string accion { get; set; }
        public decimal idcliente { get; set; }
        public string contacto { get; set; }
        public string detalle { get; set; }
        public decimal idproducto { get; set; }
        public decimal cant_producto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual productos productos { get; set; }
    }
}
