//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.despacho = new HashSet<despacho>();
        }
    
        public decimal codigo_producto { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion { get; set; }
        public string udm { get; set; }
        public double costo { get; set; }
        public Nullable<decimal> existencia { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<despacho> despacho { get; set; }
    }
}
